version: 2

models:
  - name: int_order_shipping
    description: Delivery address information for each order plus shipping information
    columns:
      - name: address_id
        description: UUID for each unique address on platform
        tests:
          - not_null
      - name: zipcode
        description: ZIP code of the address (cleaned to account for dropped leading zeroes)
      - name: is_usa
        description: Indicates whether the address country is United States

  - name: int_user_orders
    description: Order information combined with the user information
    columns: 
      - name: order_id
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null

  - name: int_product_orders
    description: Overall product level information, including number of orders containing a product
    columns: 
      - name: product_id
        tests:
          - not_null
          - unique
    