version: 2

models:
  - name: int_shipping
    description: Delivery address information for each order plus shipping information
    columns:
      - name: address_id
        description: UUID for each unique address on platform
        tests:
          - not_null
      - name: zipcode
        description: ZIP code of the address (cleaned to account for dropped leading zeroes)
        tests:
          - zip_code_length
      - name: is_usa
        description: Indicates whether the address country is United States

  - name: int_users
    description: User information including number of orders made
    columns:
      - name: user_id

  - name: int_orders
    description: Order information with promo code information
    tests: 
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - user_id
            - order_id

  - name: int_products
    description: Product level informaiton
    columns:
      - name: number_in_stock
        tests: 
          - positive_values
      - name: number_of_orders_with_product
        tests: 
          - positive_values
    