version: 2

models:
  - name: stg_addresses
    description: Delivery address information for each order
    columns:
      - name: address_id
        description: UUID for each unique address on platform
        tests:
          - not_null
          - unique
      - name: address
        description: The first few lines of the address
      - name: zipcode
        description: ZIP code of the address
      - name: state
        description: State of the address     
      - name: country
        description: Country of the address

  - name: stg_events
    description: Event information for each user
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: session_id
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: page_url
        tests:
          - not_null
      - name: created_at
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
          - accepted_values: 
             values: ['add_to_cart','checkout','page_view','package_shipped']

  - name: stg_order_items
    description: Quantity and product information for each order
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
          - positive_values

  - name: stg_orders
    description: Order information
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests: 
          - not_null
      - name: address_id
        tests: 
          - not_null
      - name: created_at
        tests: 
          - not_null
      - name: order_cost
        tests:
          - not_null
          - positive_values
      - name: order_total
        tests: 
          - not_null
          - positive_values
      - name: status
        tests:
          - not_null
          - accepted_values: 
             values: ['shipped', 'preparing', 'delivered']
          
  - name: stg_products
    description: Product and inventory information
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: name
          - not_null
      - name: price
        tests:
         - positive_values

  - name: stg_promos
    description: Promo code information
    columns:
      - name: promo_id
        tests:
          - not_null
          - unique
      - name: status
        tests:
          - accepted_values:
             values: ['active', 'inactive'] 
      - name: discount
        tests:
          - positive_values

  - name: stg_users
    description: User information
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests: 
          - not_null
      - name: email
        tests: 
          - not_null
      - name: phone_number
        tests: 
          - not_null
      - name: created_at
        tests: 
          - not_null
      - name: updated_at
        tests: 
          - not_null
      - name: address_id
        tests: 
          - not_null


