version: 2

models:
  - name: int_order_products
    description: Order level information with product names and quantities
    columns: 
      - name: order_id
        tests:
          - not_null
    