version: 2

models:
  - name: fct_sessions
    description: User information and events for each session
  - name: fct_page_views
    description: Page view events

  - name: fct_product_conversion_rates
    description: Conversion rate at the product level
    columns: 
      - name: product_id
        tests:
          - not_null
          - unique
      - name: product_name
        tests:
          - not_null
          - unique
      - name: product_conversion_rate
        description: Calculated as the number of unique sessions with a purchase event of that product divided by the total number of unique sessions that viewed that product
        tests: 
          - positive_values