version: 2

models:
  - name: fct_user_orders
    description: Order information combined with the user and promo information
    columns: 
      - name: user_id
        tests:
          - not_null

  - name: dim_users
    description: Information for each Greenery user
    columns: 
      - name: user_id
        tests:
          - not_null
          - unique
    