version: 2

models:
  - name: fct_user_orders
    description: Order information combined with the user and promo information
    columns: 
      - name: user_id
        tests:
          - not_null
          